// =============================================================================
// PayloadKey.h - GENERATED, DO NOT EDIT BY HAND
// =============================================================================
// Generated by tools/encrypt_payload.py. Regenerate by deleting this file
// and rebuilding, or by passing --regen-key. The shim's compiled-in copy
// of these bytes must match the key used to encrypt bin/payload.bin -
// any drift and decryption produces garbage that fails PE validation.
// =============================================================================
#pragma once

namespace ENI::Crypt {

inline constexpr KeyMaterial PayloadKey = {{
    0xDD, 0xCE, 0x22, 0xA9, 0x0F, 0x68, 0xAC, 0x7A,
    0xAA, 0x14, 0x11, 0xF9, 0xA1, 0x37, 0x65, 0x20,
    0xF7, 0xA8, 0x3F, 0xC9, 0x37, 0x5B, 0x79, 0x55,
    0x9D, 0xE8, 0xF5, 0x44, 0x37, 0x88, 0x57, 0x95,
}};

} // namespace ENI::Crypt
