#!/usr/bin/env python3
# =============================================================================
# encrypt_payload.py - build-time payload encryption + key generation
# =============================================================================
#
# Usage (typically driven by CMake POST_BUILD on ENIPayload):
#
#   python tools/encrypt_payload.py \
#       --in  bin/ENIPayload.dll \
#       --out bin/payload.bin \
#       --key-header shared/PayloadKey.h
#
# What it does:
#
#   1. Reads --in (the freshly built ENIPayload.dll plaintext PE).
#   2. If --key-header doesn't exist or --regen-key is passed, generates
#      a fresh 32-byte ChaCha20 key with secrets.token_bytes() and writes
#      it as a C++ header (matching the KeyMaterial layout in
#      shared/PayloadCrypt.h). Otherwise reuses the existing key so
#      incremental builds don't re-encrypt-and-rebuild-shim on every
#      iteration.
#   3. Generates a fresh 12-byte nonce per encryption (token_bytes too).
#   4. ChaCha20-encrypts the payload with that key+nonce.
#   5. Writes magic(4) || nonce(12) || ciphertext to --out.
#
# The key is per-build, not per-encryption. The shim has it baked in;
# regenerating it requires recompiling the shim. Nonce is per-encryption
# so even repeated encryptions of the same plaintext produce different
# ciphertext on disk.
#
# This script intentionally has zero third-party dependencies. The
# ChaCha20 implementation below is RFC 7539 reference - it must produce
# byte-identical output to shared/PayloadCrypt.h's C++ implementation
# or the shim will fail to decrypt.
# =============================================================================

from __future__ import annotations

import argparse
import os
import secrets
import struct
import sys
from pathlib import Path

# Mirrors ENI::Crypt::PayloadMagic in shared/PayloadCrypt.h
PAYLOAD_MAGIC = 0x45494E45  # "ENIE" little-endian


def _rotl32(v: int, n: int) -> int:
    v &= 0xFFFFFFFF
    return ((v << n) | (v >> (32 - n))) & 0xFFFFFFFF


def _quarter(state: list[int], a: int, b: int, c: int, d: int) -> None:
    state[a] = (state[a] + state[b]) & 0xFFFFFFFF
    state[d] = _rotl32(state[d] ^ state[a], 16)
    state[c] = (state[c] + state[d]) & 0xFFFFFFFF
    state[b] = _rotl32(state[b] ^ state[c], 12)
    state[a] = (state[a] + state[b]) & 0xFFFFFFFF
    state[d] = _rotl32(state[d] ^ state[a],  8)
    state[c] = (state[c] + state[d]) & 0xFFFFFFFF
    state[b] = _rotl32(state[b] ^ state[c],  7)


def _block(key: bytes, counter: int, nonce: bytes) -> bytes:
    """Generate one 64-byte ChaCha20 keystream block. RFC 7539 §2.3."""
    assert len(key) == 32
    assert len(nonce) == 12
    consts = (0x61707865, 0x3320646E, 0x79622D32, 0x6B206574)
    key_words   = struct.unpack("<8I", key)
    nonce_words = struct.unpack("<3I", nonce)
    state = list(consts) + list(key_words) + [counter & 0xFFFFFFFF] + list(nonce_words)
    working = state[:]
    for _ in range(10):
        # Column rounds
        _quarter(working, 0, 4,  8, 12)
        _quarter(working, 1, 5,  9, 13)
        _quarter(working, 2, 6, 10, 14)
        _quarter(working, 3, 7, 11, 15)
        # Diagonal rounds
        _quarter(working, 0, 5, 10, 15)
        _quarter(working, 1, 6, 11, 12)
        _quarter(working, 2, 7,  8, 13)
        _quarter(working, 3, 4,  9, 14)
    summed = [(working[i] + state[i]) & 0xFFFFFFFF for i in range(16)]
    return struct.pack("<16I", *summed)


def chacha20_xor(key: bytes, nonce: bytes, data: bytes) -> bytes:
    """ChaCha20 stream cipher. Counter starts at 1 per RFC 7539
    convention (block 0 reserved for AEAD keying). Symmetric: same
    function encrypts and decrypts."""
    out = bytearray(len(data))
    counter = 1
    for offset in range(0, len(data), 64):
        ks = _block(key, counter, nonce)
        chunk = data[offset:offset + 64]
        for i, b in enumerate(chunk):
            out[offset + i] = b ^ ks[i]
        counter += 1
    return bytes(out)


def write_key_header(path: Path, key: bytes) -> None:
    """Emit shared/PayloadKey.h that PayloadCrypt.h #includes when present.
    The format must match the KeyMaterial struct exactly."""
    assert len(key) == 32
    rows = []
    for i in range(0, 32, 8):
        row = ", ".join(f"0x{b:02X}" for b in key[i:i + 8])
        rows.append(f"    {row},")
    body = "\n".join(rows)
    header = f"""// =============================================================================
// PayloadKey.h - GENERATED, DO NOT EDIT BY HAND
// =============================================================================
// Generated by tools/encrypt_payload.py. Regenerate by deleting this file
// and rebuilding, or by passing --regen-key. The shim's compiled-in copy
// of these bytes must match the key used to encrypt bin/payload.bin -
// any drift and decryption produces garbage that fails PE validation.
// =============================================================================
#pragma once

namespace ENI::Crypt {{

inline constexpr KeyMaterial PayloadKey = {{{{
{body}
}}}};

}} // namespace ENI::Crypt
"""
    path.write_text(header, encoding="ascii")


def load_or_generate_key(header_path: Path, regen: bool) -> bytes:
    """Read the 32 key bytes back out of an existing PayloadKey.h, or
    generate a fresh key if the header is missing / --regen-key was
    passed. Re-using an existing key on incremental builds is essential -
    otherwise every payload rebuild forces a shim rebuild too, which
    nukes the build cache."""
    if regen or not header_path.exists():
        key = secrets.token_bytes(32)
        write_key_header(header_path, key)
        return key

    text = header_path.read_text(encoding="ascii")
    # Pull all 0xNN tokens. Brittle but works for the format we emit.
    import re
    matches = re.findall(r"0x([0-9A-Fa-f]{2})", text)
    if len(matches) < 32:
        # Header is corrupted or hand-edited - regenerate.
        key = secrets.token_bytes(32)
        write_key_header(header_path, key)
        return key
    return bytes(int(m, 16) for m in matches[:32])


def main() -> int:
    p = argparse.ArgumentParser(description="Encrypt payload DLL with ChaCha20")
    p.add_argument("--in", dest="src", required=True, type=Path,
                   help="Input plaintext PE (e.g. bin/ENIPayload.dll)")
    p.add_argument("--out", dest="dst", required=True, type=Path,
                   help="Output encrypted blob (e.g. bin/payload.bin)")
    p.add_argument("--key-header", required=True, type=Path,
                   help="Path to generated PayloadKey.h - written if absent, read if present")
    p.add_argument("--regen-key", action="store_true",
                   help="Force regeneration of the key (forces shim rebuild)")
    args = p.parse_args()

    if not args.src.exists():
        print(f"error: input file not found: {args.src}", file=sys.stderr)
        return 1

    args.key_header.parent.mkdir(parents=True, exist_ok=True)
    args.dst.parent.mkdir(parents=True, exist_ok=True)

    key = load_or_generate_key(args.key_header, args.regen_key)
    nonce = secrets.token_bytes(12)

    plaintext = args.src.read_bytes()
    ciphertext = chacha20_xor(key, nonce, plaintext)

    blob = struct.pack("<I", PAYLOAD_MAGIC) + nonce + ciphertext
    args.dst.write_bytes(blob)

    print(f"[encrypt_payload] {args.src.name}: {len(plaintext)} bytes -> "
          f"{args.dst.name}: {len(blob)} bytes "
          f"(key={args.key_header.name}, nonce=12B random)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
